### ISSUE TITLE
Add pagination to dashboard service

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/cgp-dashboard-service#39]
as an end user I would like  to be able to page through search results in the fie browser and handle searches that exceed the ES limit
 Boardwalk backend

**Comment by kozbo** [comment]
- [ ] Create a large test input index file 
- [ ] implement the search after method in ES (in Kibana)
- [ ]  wrap up in a Python method

**Comment by cricketsloan** [comment]
@caaespin I am putting this into your court for overall design plan.  We still think it is important
